<?php
return [
    'all' => [
        'primary',
        'secondary',
        'light',
        'dark',
        'red',
        'orange',
        'amber',
        'yellow',
        'lime',
        'green',
        'emerald',
        'teal',
        'cyan',
        'sky',
        'blue',
        'indigo',
        'violet',
        'purple',
        'fuchsia',
        'pink',
        'rose',
        'slate',
        'gray',
        'zinc',
        'neutral',
        'stone',
        'info',
        'success',
        'warning',
        'error',
    ],
    'admin' => 'pink',
    'writer' => 'emerald',
    'editor' => 'blue',
    'member' => 'green',
    'guest' => 'gray',
];
