<?php
return [
    'user' => 'bi-person-fill',
    'role' => 'bi-person-cog',
    'permission' => 'bi-key-fill',
    'post' => 'bi-newspaper',
    'category' => 'bi-folder-fill',
    'tag' => 'bi-tag-fill',
    'media' => 'bi-image',
    'setting' => 'bi-gear-wide-connected',
    'admin' => 'bi-person-badge',
    'writer' => 'bi-pencil-square',
    'editor' => 'bi-scissors',
    'member' => 'bi-people',
    'guest' => 'bi-person',
    'manage_users' => 'bi-person-lines-fill',
    'manage_roles' => 'bi-shield-lock',
    'manage_permissions' => 'bi-key',
    'manage_posts' => 'bi-file-earmark-text',
    'manage_pages' => 'bi-file-earmark-richtext',
    'manage_media' => 'bi-images',
    'manage_settings' => 'bi-gear',
    'manage_categories' => 'bi-folder-fill',
];
